---
- name: 'Configure the node'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.minimal_bashrc'
      additional_users: "{{ ansible_user }}"
    - role: 'johanneskastl.create_a_vimrc'
      additional_users: "{{ ansible_user }}"

- name: 'Install rke2'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_rke2'
