---
- name: 'Configure the node'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'minimal_bashrc'
      vars:
        additional_users: "{{ ansible_user }}"
    - role: 'create_a_vimrc'
      vars:
        additional_users: "{{ ansible_user }}"

- name: 'Install rke2'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'install_rke2'
